# Generated by Django 2.0 on 2017-12-06 09:27

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
    ]