# Generated by Django 2.0 on 2017-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20171206_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(default='', max_length=255),
        ),
    ]
