# Generated by Django 2.0 on 2017-12-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20171206_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='name',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
    ]
