# Generated by Django 2.0 on 2017-12-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20171206_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='attendee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
