# Generated by Django 2.0 on 2017-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20171206_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(to='quickstart.Event'),
        ),
    ]
