# Generated by Django 2.0 on 2017-12-06 17:30

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_attendee_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begins',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
